### ISSUE TITLE
Support for Cloud SQL 

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/metadata#201]
Is it possible to use Google Cloud SQL as the backing store for the metadata service? If so, how can this be done?

**Comment by parthmishra** [comment]
I think I figured out how to do this with Kustomize. I added the following to my `kustomization.yaml`:

```
secretGenerator:
  - name: mysql-credential
    behavior: replace
    file:
      - cloudsql-credentials
```

The `metadata-deployment` was getting the username and password from the `mysql-credential` secret while the pipelines weren't?

Anyways, it works now as far as I can tell. I guess this issue can be closed but I feel like this should be addressed in the GCP patch file.
