### ISSUE TITLE
Error: json: unknown field "env"

### ISSUE THREAD

**Issue by andrewm4894** [kubeflow/metadata#202]
/kind bug

I'm trying to install metadata onto my gcp kubeflow following the docs [here](https://www.kubeflow.org/docs/components/misc/metadata/). 

However when i run
```
cd manifests/metadata/base
kustomize build . | kubectl apply -n kubeflow -f -
```

I get this error:
```
$:~/manifests/metadata/base$ kustomize build . | kubectl apply -n kubeflow -f -
Error: json: unknown field "env"
error: no objects passed to apply
```
I found [this issue](https://github.com/kubernetes-sigs/kustomize/issues/1069) which seems to suggest whats going on. But i have no idea how to implement a work around to get metadata install on my cluster. 

It feels like might be easy enough but unfortunately i really don't know what i'm doing when it comes to kubeflow and kubernetes troubleshooting.  

Has anyone else run into this?

## Enviornment
- Metadata version: metadata-v0.7.0
- Kubeflow version: kubeflow-v0.7.0
- Kubernetes version: (use kubectl version): 1.14.9-gke.2

**Comment by zhenghuiwang** [comment]
I think you're right: It is `kustomize` issue as I tried to run it locally and it works.

My version:
```
$ kustomize version                                                                    
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}
```

What version do you use?

Also, you can try the new overlay to install it:

```
cd manifests/metadata
kustomize build overlays/db | kubectl apply -n kubeflow -f -
```

**Comment by parthmishra** [comment]
Changing instances of `env` to `envs` and putting the values in a list resolved this issue for me.

**Comment by andrewm4894** [comment]
> Changing instances of `env` to `envs` and putting the values in a list resolved this issue for me.

@parthmishra would you be able to give me some info/tips/pointers on how to do this? Apologies but i'm a total newbie here so not sure how/where to change these references.

**Comment by parthmishra** [comment]
Sure,  in `overlays/db/kustomization.yaml` file, I commented out the `env` and replaced with `envs` as shown below:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
namespace: kubeflow
generatorOptions:
  # name suffix hash is not propagated correctly to base resources
  disableNameSuffixHash: true
configMapGenerator:
  - name: metadata-db-parameters
    # env: params.env
    envs:
      - params.env
secretGenerator:
  - name: metadata-db-secrets
    # env: secrets.env
    envs:
      - secrets.env
...
```

**Comment by andrewm4894** [comment]
Thanks! 

Unfortunately i'm now getting this error:

```
Error: json: cannot unmarshal string into Go struct field ConfigMapArgs.envs of type []string
error: no objects passed to apply
```
My `overlays/db/kustomization.yaml` looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
namespace: kubeflow
generatorOptions:
  # name suffix hash is not propagated correctly to base resources
  disableNameSuffixHash: true
configMapGenerator:
- name: metadata-db-parameters
  envs: params.env
secretGenerator:
- name: metadata-db-secrets
  envs: secrets.env
bases:
- ../../base
resources:
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml
patchesStrategicMerge:
- metadata-deployment.yaml
images:
- name: mysql
  newName: mysql
  newTag: 8.0.3
vars:
- name: metadata-db-service
  objref:
    kind: Service
    name: metadata-db
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```

If i run `kustomize version` i see:
```
Version: {Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```
I think that might be because i installed it via [these instructions](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#build-the-kustomize-cli-from-local-source) but i believe that should be the latest.

**Comment by andrewm4894** [comment]
Seems like [this issue](https://github.com/kubernetes-sigs/kustomize/issues/1373) is related to my new error. Googling furiously.

**Comment by parthmishra** [comment]
You need to change 
```yaml
envs: secrets.env
```
to 
```yaml
envs:
  - secrets.env
```
And repeat for `envs: params.env` 

The top portion is interpreted as a string and thus causing the error when it's supposed to be a list.

**Comment by andrewm4894** [comment]
Now i'm getting:
```
Error: accumulating resources: couldn't make target for path '../../base': json: unknown field "env"
error: no objects passed to apply
```

`overlays/db/kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
namespace: kubeflow
generatorOptions:
  # name suffix hash is not propagated correctly to base resources
  disableNameSuffixHash: true
configMapGenerator:
- name: metadata-db-parameters
  envs: 
    - params.env
secretGenerator:
- name: metadata-db-secrets
  envs: 
    - secrets.env
bases:
- ../../base
resources:
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml
patchesStrategicMerge:
- metadata-deployment.yaml
images:
- name: mysql
  newName: mysql
  newTag: 8.0.3
vars:
- name: metadata-db-service
  objref:
    kind: Service
    name: metadata-db
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```

Apologies for the back and forth, hopefully might be useful for others who might run into this.

**Comment by parthmishra** [comment]
Ah that's my bad, I forgot to say that you need to do this in the base file as well (`base/kustomization.yaml`). Edit any instances of `env` to `envs` like you did with the overlays.

**Comment by andrewm4894** [comment]
Thanks! I got a load of output so looks like it did something :)

Will try work through one of the metadata pipelines to confirm.

**Comment by andrewm4894** [comment]
Although last line of output said:

```
for: "STDIN": Deployment.apps "metadata-ui" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"metadata-ui", "kustomize
.component":"metadata"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

But not sure if that's a non issue or not.

**Comment by squaricdot** [comment]
okay moving to envs worked. is this just happening because i downloaded the latest available kustomize ? is there any up to date documentation about what keys to use, or are valid in regards of latest version or updates.

it was rather unclear.

**Comment by Manvi07** [comment]
Hi @parthmishra 

I am facing a similar issue, what 
```
kustomize build overlays/db
Error: json: cannot unmarshal array into Go struct field ConfigMapArgs.configMapGenerator.env of type string
```
Please let me know how I should change my file.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
namespace: kubeflow
generatorOptions:
  # name suffix hash is not propagated correctly to base resources
  disableNameSuffixHash: true
configMapGenerator:
- name: metadata-db-parameters
  env:
  - param.env
secretGenerator:
- name: metadata-db-secrets
  env:
  - secret.env
bases:
- ../../base
resources:
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml
patchesStrategicMerge:
- metadata-deployment.yaml
images:
- name: mysql
  newName: mysql
  newTag: 8.0.3
vars:
- name: metadata-db-service
  objref:
    kind: Service
    name: metadata-db
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```
